routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/session/user', function () {
    return Auth::user();
})->name('session.user');

Route::get('/', 'WelcomeController@welcome')->name('welcome');
Route::get('/error', 'HomeController@error')->name('error');
Route::get('/forbidden', 'HomeController@forbidden')->name('forbidden');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/info', 'UserController@info')->name('info');
    Route::get('/user/balance', 'BalanceHistoryController@show')->name('balance');

    Route::group(['prefix' => 'admin'],function () {
        Route::resource('/role', 'RoleController')
            ->middleware('permission:admin role');

        Route::resource('/user', 'UserController')
            ->middleware('permission:admin user')
            ->except(['store', 'create']);
    });

    /*
     * Creator routes
     */
    Route::group(['prefix' => 'creator'], function () {
        Route::resource('/category', 'CategoryController')
            ->middleware('permission:creator category');

        Route::resource('/subcategory', 'SubcategoryController')
            ->middleware('permission:creator subcategory');

        Route::resource('/team', 'TeamController')
            ->middleware('permission:creator team');

        Route::resource('/event', 'EventController')
            ->middleware('permission:creator event')
            ->except(['create', 'store']);
    });

    /*
     * Company routes
     */
    Route::group(['prefix' => 'company'], function () {
        Route::get('/bets', 'BetController@index')
            ->middleware('permission:company all bets')
            ->name('company.bets');

        Route::get('/bets/open', 'BetController@companyOpenBets')
            ->middleware('permission:company open bets')
            ->name('company.open.bets');

        Route::get('/bets/closed', 'BetController@companyClosedBets')
            ->middleware('permission:company closed bets')
            ->name('company.closed.bets');

        Route::resource('/bonus', 'BonusController')
            ->middleware('permission:company bonus')
            ->only(['index', 'create', 'store']);

        Route::post('/bonus/activate/{bonus}', 'BonusController@activate')
            ->middleware('permission:company bonus activate')
            ->name('bonus.activate');

        Route::post('/bonus/deactivate}', 'BonusController@deactivate')
            ->middleware('permission:company bonus deactivate')
            ->name('bonus.deactivate');
    });

    /*
     *  Player routes
    */
    Route::group(['prefix' => 'player'], function () {
        Route::get('/events/available', 'EventController@showAvailableEvents')
            ->middleware('permission:player events and bets')
            ->name('player.available.events');

        Route::get('/bets/open', 'BetController@playerOpenBets')
            ->middleware('permission:player open bets')
            ->name('player.open.bets');

        Route::get('/bets/closed', 'BetController@playerClosedBets')
            ->middleware('permission:player closed bets')
            ->name('player.closed.bets');

        Route::get('/statistic', 'Statistic\PlayerController@index')
            ->middleware('permission:player statistic')
            ->name('player.statistic');
    });
});

app/Subcategory.php
<?php

declare (strict_types=1);

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class Subcategory
 *
 * @package App
 * @property-read Category $category
 * @property-read Team $team
 * @mixin \Eloquent
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $description
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static Builder|Subcategory whereCategoryId($value)
 * @method static Builder|Subcategory whereCreatedAt($value)
 * @method static Builder|Subcategory whereDescription($value)
 * @method static Builder|Subcategory whereId($value)
 * @method static Builder|Subcategory whereName($value)
 * @method static Builder|Subcategory whereUpdatedAt($value)
 * @method static Builder|Subcategory newModelQuery()
 * @method static Builder|Subcategory newQuery()
 * @method static Builder|Subcategory query()
 */
class Subcategory extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'category_id',
    ];

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsTo
     */
    public function team(): BelongsTo
    {
        return $this->belongsTo(Team::class);
    }
}

app/Http/Controllers/SubcategoryController.php
<?php

declare (strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\SubcategoryStoreRequest;
use App\Http\Requests\SubcategoryUpdateRequest;
use App\Repositories\CategoryRepository;
use App\Repositories\SubcategoryRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class SubcategoryController extends Controller
{
    /**
     * @var SubcategoryRepository
     */
    private $subcategoryRepository;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository,SubcategoryRepository $subcategoryRepository)
    {
        $this->subcategoryRepository = $subcategoryRepository;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {
        $subcategories = $this->subcategoryRepository->paginate();

        return view('subcategory.list', compact('subcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     * @throws \Exception
     */
    public function create(): View
    {
        $categories = $this->categoryRepository->all();

        return view('subcategory.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SubcategoryStoreRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(SubcategoryStoreRequest $request): RedirectResponse
    {
        $this->subcategoryRepository->create([
            'name' => $request->getName(),
            'description' => $request->getDescription(),
            'category_id' => $request->getCategoryId(),
        ]);

        return redirect()
            ->route('subcategory.index')
            ->with('status', 'Subcategory created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $subcategoryId
     * @return View
     * @throws \Exception
     */
    public function show(int $subcategoryId): View
    {
        $subcategory = $this->subcategoryRepository->find($subcategoryId);

        return view('subcategory.view', compact('subcategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $subcategoryId
     * @return View
     * @throws \Exception
     */
    public function edit(int $subcategoryId): View
    {
        $categories = $this->categoryRepository->all();

        $subcategory = $this->subcategoryRepository->find($subcategoryId);

        return view('subcategory.edit', compact('subcategory', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param SubcategoryUpdateRequest $request
     * @param int $subcategoryId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(SubcategoryUpdateRequest $request, int $subcategoryId): RedirectResponse
    {
        $data = [
        'name' => $request->getName(),
        'description' => $request->getDescription(),
        'category_id' => $request->getCategoryId(),
        ];

        $this->subcategoryRepository->update($data, $subcategoryId);

        return redirect()
            ->route('subcategory.index')
            ->with('status', 'Subcategory updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $subcategoryId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(int $subcategoryId): RedirectResponse
    {
        $this->subcategoryRepository->delete(['id' => $subcategoryId]);

        return redirect()
            ->route('subcategory.index')
            ->with('status', 'Subcategory deleted successfully');
    }
}

resources/views/subcategory/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Subcategory New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('subcategory.store') }}" method="post">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description') }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="category_id">{{ __('Category') }}:</label>
                                <select name="category_id" id="category_id" class="form-control">
                                    <option value="" selected disabled>Select category</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ (old('category_id') == $category->id)? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="alert-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('subcategory.index') }}>Back to list</a>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/subcategory/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Subcategory Edit
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('subcategory.update', [$subcategory->id]) }}" method="post">

                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name', $subcategory->name) }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description', $subcategory->description) }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="category_id">{{ __('Category') }}:</label>
                                <select name="category_id" id="category_id" class="form-control">
                                    <option value="" selected disabled>Select category</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ (old('category_id', $subcategory->category->id) == $category->id)? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="alert-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('subcategory.index') }}>Back to list</a>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/subcategory/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Subcategories List
                        <a class="btn btn-sm btn-primary" href="{{ route('subcategory.create') }}">{{ __('New') }}</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                            @foreach($subcategories as $subcategory)
                                <tr>
                                    <td>{{ $subcategory->id }}</td>
                                    <td>
                                        <a href="{{ route('subcategory.show', [$subcategory->id]) }}">
                                            {{ $subcategory->name }}
                                        </a>
                                    </td>
                                    <td>{{ $subcategory->description }}</td>
                                    <td>
                                        <a class='btn btn-sm btn-info' href="{{ route('subcategory.show', [$subcategory->id]) }}">{{ __('View') }}</a>
                                        <a class='btn btn-sm btn-success' href="{{ route('subcategory.edit', [$subcategory->id]) }}">{{ __('Edit') }}</a>
                                        <form action="{{ route('subcategory.destroy', [$subcategory->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                                            @method('delete')
                                            @csrf
                                            <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        {{ $subcategories->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/subcategory/view.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Subcategory View: {{ $subcategory->Name }}
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <td>{{ __('ID') }}</td>
                                <td>{{ $subcategory->id }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Name') }}</td>
                                <td>{{ $subcategory->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Description') }}</td>
                                <td>{{ $subcategory->description }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Category') }}</td>
                                <td>{{ $subcategory->category->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Created at') }}</td>
                                <td>{{ $subcategory->created_at }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Updated at') }}</td>
                                <td>{{ $subcategory->updated_at }}</td>
                            </tr>
                        </table>

                        <a class='btn btn-secondary btn-sm' href={{ route('subcategory.index') }}>Back to list</a>
                        <a class='btn btn-success btn-sm' href={{ route('subcategory.edit', [$subcategory->id]) }}>Edit</a>
                        <form action="{{ route('subcategory.destroy', [$subcategory->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                            @method('delete')
                            @csrf
                            <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection