routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/session/user', function () {
    return Auth::user();
})->name('session.user');

Route::get('/', 'WelcomeController@welcome')->name('welcome');
Route::get('/error', 'HomeController@error')->name('error');
Route::get('/forbidden', 'HomeController@forbidden')->name('forbidden');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/info', 'UserController@info')->name('info');
    Route::get('/user/balance', 'BalanceHistoryController@show')->name('balance');

    Route::group(['prefix' => 'admin'],function () {
        Route::resource('/role', 'RoleController')
            ->middleware('permission:admin role');

        Route::resource('/user', 'UserController')
            ->middleware('permission:admin user')
            ->except(['store', 'create']);
    });

    /*
     * Creator routes
     */
    Route::group(['prefix' => 'creator'], function () {
        Route::resource('/category', 'CategoryController')
            ->middleware('permission:creator category');

        Route::resource('/subcategory', 'SubcategoryController')
            ->middleware('permission:creator subcategory');

        Route::resource('/team', 'TeamController')
            ->middleware('permission:creator team');

        Route::resource('/event', 'EventController')
            ->middleware('permission:creator event')
            ->except(['create', 'store']);
    });

    /*
     * Company routes
     */
    Route::group(['prefix' => 'company'], function () {
        Route::get('/bets', 'BetController@index')
            ->middleware('permission:company all bets')
            ->name('company.bets');

        Route::get('/bets/open', 'BetController@companyOpenBets')
            ->middleware('permission:company open bets')
            ->name('company.open.bets');

        Route::get('/bets/closed', 'BetController@companyClosedBets')
            ->middleware('permission:company closed bets')
            ->name('company.closed.bets');

        Route::resource('/bonus', 'BonusController')
            ->middleware('permission:company bonus')
            ->only(['index', 'create', 'store']);

        Route::post('/bonus/activate/{bonus}', 'BonusController@activate')
            ->middleware('permission:company bonus activate')
            ->name('bonus.activate');

        Route::post('/bonus/deactivate}', 'BonusController@deactivate')
            ->middleware('permission:company bonus deactivate')
            ->name('bonus.deactivate');
    });

    /*
     *  Player routes
    */
    Route::group(['prefix' => 'player'], function () {
        Route::get('/events/available', 'EventController@showAvailableEvents')
            ->middleware('permission:player events and bets')
            ->name('player.available.events');

        Route::get('/bets/open', 'BetController@playerOpenBets')
            ->middleware('permission:player open bets')
            ->name('player.open.bets');

        Route::get('/bets/closed', 'BetController@playerClosedBets')
            ->middleware('permission:player closed bets')
            ->name('player.closed.bets');

        Route::get('/statistic', 'Statistic\PlayerController@index')
            ->middleware('permission:player statistic')
            ->name('player.statistic');
    });
});

app/Category.php
<?php

declare (strict_types=1);

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * App\Category
 *
 * @property-read Collection|Subcategory[] $subcategories
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string $description
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property int $score_from
 * @property int $score_to
 * @method static Builder|Category whereCreatedAt($value)
 * @method static Builder|Category whereDescription($value)
 * @method static Builder|Category whereId($value)
 * @method static Builder|Category whereName($value)
 * @method static Builder|Category whereScoreFrom($value)
 * @method static Builder|Category whereScoreTo($value)
 * @method static Builder|Category whereUpdatedAt($value)
 * @method static Builder|Category newModelQuery()
 * @method static Builder|Category newQuery()
 * @method static Builder|Category query()
 */
class Category extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'score_from',
        'score_to',
    ];

    /**
     * @return HasMany
     */
    public function subcategories(): HasMany
    {
        return $this->hasMany(Subcategory::class);
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

declare(strict_types = 1);

namespace App\Http\Controllers\API;

use App\Services\API\CategoryService;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;

/**
 * Class CategoryController
 * @package App\Http\Controllers\API
 */
class CategoryController extends Controller
{
    /**
     * @var CategoryService
     */
    private $categoryService;

    /**
     * CategoryController constructor.
     * @param CategoryService $categoryService
     */
    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * @return Builder[]|Collection
     * @throws \Exception
     */
    public function index()
    {
        return $this->categoryService->categoriesWithSubcategories();
    }
}

app/Http/Controllers/CategoryController.php
<?php

declare (strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;
use App\Repositories\CategoryRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    public function __construct(CategoryRepository $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {
        $categories = $this->categoryRepository->paginate();

        return view('category.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('category.create');
    }

    /**
     * @param CategoryStoreRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(CategoryStoreRequest $request)
    {
        $this->categoryRepository->create([
            'name' => $request->getName(),
            'description' => $request->getDescription(),
            'score_from' => $request->getScoreFrom(),
            'score_to' => $request->getScoreTo(),
        ]);

        return redirect()
            ->route('category.index')
            ->with('status', 'Category created successfully!');
    }

    /**
     * @param int $categoryId
     * @return View
     * @throws \Exception
     */
    public function show(int $categoryId): View
    {
        $category = $this->categoryRepository->find($categoryId);

        return view('category.view', compact('category'));
    }

    /**
     * @param int $categoryId
     * @return \Illuminate\Contracts\View\Factory|View
     * @throws \Exception
     */
    public function edit(int $categoryId)
    {
        $category = $this->categoryRepository->find($categoryId);

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryUpdateRequest $request
     * @param int $categoryId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(CategoryUpdateRequest $request, int $categoryId): RedirectResponse
    {
        $data = [
            'name' => $request->getName(),
        'description' => $request->getDescription(),
        'score_from' => $request->getScoreFrom(),
        'score_to' => $request->getScoreTo(),
        ];

        $this->categoryRepository->update($data, $categoryId);

        return redirect()
            ->route('category.index')
            ->with('status', 'Category updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $categoryId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(int $categoryId): RedirectResponse
    {
        $this->categoryRepository->delete(['id' => $categoryId]);

        return redirect()
            ->route('category.index')
            ->with('status', 'Category deleted successfully!');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Category New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('category.store') }}" method="post">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description') }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="score_from">{{ __('Score from') }}:</label>
                                <input id="score_from" class="form-control" type="number" name="score_from"
                                       value="{{ old('score_from') }}">
                                @if($errors->has('score_from'))
                                    <div class="alert-danger">{{ $errors->first('score_from') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="score_to">{{ __('Score to') }}:</label>
                                <input id="score_to" class="form-control" type="number" name="score_to"
                                       value="{{ old('score_to') }}">
                                @if($errors->has('score_to'))
                                    <div class="alert-danger">{{ $errors->first('score_to') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('category.index') }}>Back to list</a>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Category Edit
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('category.update', [$category->id]) }}" method="post">

                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name', $category->name) }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description', $category->description) }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="score_from">{{ __('Score from') }}:</label>
                                <input id="score_from" class="form-control" type="number" name="score_from"
                                       value="{{ old('score_from', $category->score_from) }}">
                                @if($errors->has('score_from'))
                                    <div class="alert-danger">{{ $errors->first('score_from') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="score_to">{{ __('Score to') }}:</label>
                                <input id="score_to" class="form-control" type="number" name="score_to"
                                       value="{{ old('score_to', $category->score_to) }}">
                                @if($errors->has('score_to'))
                                    <div class="alert-danger">{{ $errors->first('score_to') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('category.index') }}>Back to list</a>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/category/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Categories List
                        <a class="btn btn-sm btn-primary" href="{{ route('category.create') }}">{{ __('New') }}</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Actions</th>
                            </tr>
                            @foreach($categories as $category)

                                    <tr>
                                        <td>{{ $category->id }}</td>
                                        <td>
                                            <a href="{{ route('category.show', [$category->id]) }}">
                                                {{ $category->name }}
                                            </a>
                                        </td>
                                        <td>{{ $category->description }}</td>
                                        <td>
                                            <a class='btn btn-sm btn-info' href="{{ route('category.show', [$category->id]) }}">{{ __('View') }}</a>
                                            <a class='btn btn-sm btn-success' href="{{ route('category.edit', [$category->id]) }}">{{ __('Edit') }}</a>
                                            <form action="{{ route('category.destroy', [$category->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                                                @method('delete')
                                                @csrf
                                                <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                                            </form>
                                        </td>
                                    </tr>

                            @endforeach
                        </table>
                        {{ $categories->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/category/view.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Category View: {{ $category->Name }}
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <td>{{ __('ID') }}</td>
                                <td>{{ $category->id }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Name') }}</td>
                                <td>{{ $category->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Description') }}</td>
                                <td>{{ $category->description }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Score from') }}</td>
                                <td>{{ $category->score_from }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Score to') }}</td>
                                <td>{{ $category->score_to }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Created at') }}</td>
                                <td>{{ $category->created_at }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Updated at') }}</td>
                                <td>{{ $category->updated_at }}</td>
                            </tr>
                        </table>

                        <a class='btn btn-secondary btn-sm' href={{ route('category.index') }}>Back to list</a>
                        <a class='btn btn-success btn-sm' href={{ route('category.edit', [$category->id]) }}>Edit</a>
                        <form action="{{ route('category.destroy', [$category->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                            @method('delete')
                            @csrf
                            <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection