routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/session/user', function () {
    return Auth::user();
})->name('session.user');

Route::get('/', 'WelcomeController@welcome')->name('welcome');
Route::get('/error', 'HomeController@error')->name('error');
Route::get('/forbidden', 'HomeController@forbidden')->name('forbidden');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/info', 'UserController@info')->name('info');
    Route::get('/user/balance', 'BalanceHistoryController@show')->name('balance');

    Route::group(['prefix' => 'admin'],function () {
        Route::resource('/role', 'RoleController')
            ->middleware('permission:admin role');

        Route::resource('/user', 'UserController')
            ->middleware('permission:admin user')
            ->except(['store', 'create']);
    });

    /*
     * Creator routes
     */
    Route::group(['prefix' => 'creator'], function () {
        Route::resource('/category', 'CategoryController')
            ->middleware('permission:creator category');

        Route::resource('/subcategory', 'SubcategoryController')
            ->middleware('permission:creator subcategory');

        Route::resource('/team', 'TeamController')
            ->middleware('permission:creator team');

        Route::resource('/event', 'EventController')
            ->middleware('permission:creator event')
            ->except(['create', 'store']);
    });

    /*
     * Company routes
     */
    Route::group(['prefix' => 'company'], function () {
        Route::get('/bets', 'BetController@index')
            ->middleware('permission:company all bets')
            ->name('company.bets');

        Route::get('/bets/open', 'BetController@companyOpenBets')
            ->middleware('permission:company open bets')
            ->name('company.open.bets');

        Route::get('/bets/closed', 'BetController@companyClosedBets')
            ->middleware('permission:company closed bets')
            ->name('company.closed.bets');

        Route::resource('/bonus', 'BonusController')
            ->middleware('permission:company bonus')
            ->only(['index', 'create', 'store']);

        Route::post('/bonus/activate/{bonus}', 'BonusController@activate')
            ->middleware('permission:company bonus activate')
            ->name('bonus.activate');

        Route::post('/bonus/deactivate}', 'BonusController@deactivate')
            ->middleware('permission:company bonus deactivate')
            ->name('bonus.deactivate');
    });

    /*
     *  Player routes
    */
    Route::group(['prefix' => 'player'], function () {
        Route::get('/events/available', 'EventController@showAvailableEvents')
            ->middleware('permission:player events and bets')
            ->name('player.available.events');

        Route::get('/bets/open', 'BetController@playerOpenBets')
            ->middleware('permission:player open bets')
            ->name('player.open.bets');

        Route::get('/bets/closed', 'BetController@playerClosedBets')
            ->middleware('permission:player closed bets')
            ->name('player.closed.bets');

        Route::get('/statistic', 'Statistic\PlayerController@index')
            ->middleware('permission:player statistic')
            ->name('player.statistic');
    });
});

app/Role.php
<?php

declare(strict_types = 1);

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * App\Role
 *
 * @method static create(array $array)
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string $description
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property int $active
 * @method static Builder|Role whereActive($value)
 * @method static Builder|Role whereCreatedAt($value)
 * @method static Builder|Role whereDescription($value)
 * @method static Builder|Role whereId($value)
 * @method static Builder|Role whereName($value)
 * @method static Builder|Role whereUpdatedAt($value)
 * @method static Builder|Role newModelQuery()
 * @method static Builder|Role newQuery()
 * @method static Builder|Role query()
 */
class Role extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'default',
        'full_access',
        'active',
    ];

    /**
     * @return BelongsToMany
     */
    public function permissions(): BelongsToMany
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/RoleController.php
<?php

declare (strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\RoleStoreRequest;
use App\Http\Requests\RoleUpdateRequest;
use App\Permission;
use App\Repositories\RoleRepository;
use App\Role;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Throwable;

/**
 * Class RoleController
 * @package App\Http\Controllers
 */
class RoleController extends Controller
{
    /**
     * @var RoleRepository
     */
    private $roleRepository;

    /**
     * RoleController constructor.
     * @param RoleRepository $roleRepository
     */
    public function __construct(RoleRepository $roleRepository)
    {
        $this->roleRepository = $roleRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {
        $roles = $this->roleRepository->sortBy('name')->paginate();

        return view('role.list', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $permissions = Permission::all()->sortBy('name');

        return view('role.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RoleStoreRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(RoleStoreRequest $request): RedirectResponse
    {
        /** @var Role $role */
        $role = $this->roleRepository->create([
            'name' => $request->getName(),
            'description' => $request->getDescription(),
            'default' => boolval($request->getDefault()),
            'full_access' => boolval($request->getFullAccess()),
            'active' => boolval($request->getActive()),
        ]);

        if (!boolval($request->getFullAccess())) {
            $role->permissions()->sync($request->getPermissionsIds());
        } else {
            $role->permissions()->sync([]);
        }

        return redirect()
            ->route('role.index')
            ->with('status', 'Role created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $roleId
     * @return View
     * @throws \Exception
     */
    public function show(int $roleId): View
    {
        $role = $this->roleRepository->find($roleId);

        return view('role.view', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $roleId
     * @return View
     * @throws \Exception
     */
    public function edit(int $roleId): View
    {
        $role = $this->roleRepository->with(['permissions'])->find($roleId);
        $permissions = Permission::all()->sortBy('name');

        return view('role.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RoleUpdateRequest $request
     * @param int $roleId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(RoleUpdateRequest $request, int $roleId): RedirectResponse
    {
        $data = [
            'name' => $request->getName(),
            'description' => $request->getDescription(),
            'default' => boolval($request->getDefault()),
            'full_access' => boolval($request->getFullAccess()),
            'active' => boolval($request->getActive()),
        ];

        /** @var Role $role */
        $this->roleRepository->update($data, $roleId);

        $role = $this->roleRepository->find($roleId);

        if (!boolval($request->getFullAccess())) {
            $role->permissions()->sync($request->getPermissionsIds());
        } else {
            $role->permissions()->sync([]);
        }

        return redirect()
            ->route('role.index')
            ->with('status', 'Role updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $roleId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(int $roleId): RedirectResponse
    {
        try {
            if ($this->roleRepository->delete(['id' => $roleId])) {
                return redirect()
                    ->route('role.index')
                    ->with('status', 'Role deleted successfully!');
            } else {
                return redirect()
                    ->route('role.index')
                    ->with('error', 'Role with ID: ' . $roleId . ' does not exists!');
            }
        } catch (Throwable $exception) {
            return redirect()
                ->route('role.index')
                ->with('error', $exception->getMessage());
        }
    }
}

resources/views/role/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Role New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('role.store') }}" method="post">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description') }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="default">{{ __('Default?') }}</label>
                                <input type="hidden" name="default" value="0">
                                <input id="default" type="checkbox" name="default" value="1" {{ old('default')? "checked" : "" }}>
                            </div>

                            <div class="form-group">
                                <label for="full_access">{{ __('Full access?') }}</label>
                                <input type="hidden" name="full_access" value="0">
                                <input id="full_access" type="checkbox" name="full_access" value="1" onclick="togglePermissions()" {{ old('full_access')? "checked" : "" }}>
                            </div>

                            <div class="form-group">
                                <label for="active">{{ __('Active?') }}</label>
                                <input type="hidden" name="active" value="0">
                                <input id="active" type="checkbox" name="active" value="1" {{ old('active')? "checked" : "" }}>
                            </div>

                            <div class="form-group" id="permissions">
                                <div>
                                    <label>{{ __('Available permissions') }}:</label>
                                </div>
                                <div class="container-fluid">
                                    <div class="row">
                                        @foreach($permissions as $permission)
                                            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                                <label>
                                                    <input type="checkbox" name="permissions[]" value="{{ $permission->id }}" {{ (in_array($permission->id, old('permissions', []))? 'checked': '') }}> {{ ucfirst($permission->name) }}
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('role.index') }}>Back to list</a>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function togglePermissions()
        {
            let checkToggle = document.getElementById('full_access').checked;
            let permissionsBlock = document.getElementById('permissions');
            if (checkToggle) {
                permissionsBlock.classList.add('d-none');
            } else {
                permissionsBlock.classList.remove('d-none');
            }
        }
    </script>
@endsection

resources/views/role/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Role Edit
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('role.update', [$role->id]) }}" method="post">

                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name', $role->name) }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description', $role->description) }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="default">{{ __('Default?') }}</label>
                                <input type="hidden" name="default" value="0">
                                <input id="default" type="checkbox" name="default" value="1" {{ old('default', $role->default) ? "checked" : "" }}>
                            </div>

                            <div class="form-group">
                                <label for="full_access">{{ __('Full access?') }}</label>
                                <input type="hidden" name="full_access" value="0">
                                <input id="full_access" type="checkbox" name="full_access" value="1" onclick="togglePermissions()" {{ old('full_access', $role->full_access) ? "checked" : "" }}>
                            </div>

                            <div class="form-group">
                                <label for="active">{{ __('Active?') }}</label>
                                <input type="hidden" name="active" value="0">
                                <input id="active" type="checkbox" name="active" value="1" {{ old('active', $role->active) ? "checked" : "" }}>
                            </div>

                            <div class="form-group {{old('full_access', $role->full_access) ? 'd-none' : ''}}" id="permissions">
                                <div>
                                    <label>{{ __('Available permissions') }}:</label>
                                </div>
                                <div class="container-fluid">
                                    <div class="row">
                                        @foreach($permissions as $permission)
                                            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                                <label>
                                                    <input type="checkbox" name="permissions[]" value="{{ $permission->id }}" {{ (in_array($permission->id, old('permissions', $role->permissions->pluck('id')->toArray()))? 'checked': '') }}> {{ ucfirst($permission->name) }}
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class="btn btn-secondary btn-sm" href={{ route('role.index') }}>Back to list</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function togglePermissions()
        {
            let checkToggle = document.getElementById('full_access').checked;
            let permissionsBlock = document.getElementById('permissions');
            if (checkToggle) {
                permissionsBlock.classList.add('d-none');
            } else {
                permissionsBlock.classList.remove('d-none');
            }
        }
    </script>
@endsection

resources/views/role/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Roles List
                        <a class="btn btn-sm btn-primary" href="{{ route('role.create') }}">{{ __('New') }}</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif

                        @if (count($roles) > 0)
                            <table class="table">
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Default?</th>
                                    <th>Full access?</th>
                                    <th>Active?</th>
                                    <th>Actions</th>
                                </tr>
                                @foreach($roles as $role)
                                    <tr>
                                        <td>{{ $role->id }}</td>
                                        <td>
                                            <a href="{{ route('role.show', [$role->id]) }}">
                                                {{ $role->name }}
                                            </a>
                                        </td>
                                        <td>{{ $role->description }}</td>
                                        <td class="{{ ($role->default)? "text-success": "text-danger" }}">{{ ($role->default)? "Yes": "No" }}</td>
                                        <td class="{{ ($role->full_access)? "text-success": "text-danger" }}">{{ ($role->full_access)? "Yes": "No" }}</td>
                                        <td class="{{ ($role->active)? "text-success": "text-danger" }}">{{ ($role->active)? "Active": "Inactive" }}</td>
                                        <td>
                                            <a class='btn btn-sm btn-info'
                                               href="{{ route('role.show', [$role->id]) }}">{{ __('View') }}</a>
                                            <a class='btn btn-sm btn-success'
                                               href="{{ route('role.edit', [$role->id]) }}">{{ __('Edit') }}</a>
                                            <form action="{{ route('role.destroy', [$role->id]) }}" method="post"
                                                  class="d-inline-block"
                                                  onsubmit="return confirm('Do you really want to delete?');">
                                                @method('delete')
                                                @csrf
                                                <input class="btn btn-sm btn-outline-danger" type="submit" value="Delete">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </table>
                            {{ $roles->links() }}
                        @else
                            There are no roles yet!
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/role/view.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Role View: {{ $role->Name }}
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <td>{{ __('ID') }}</td>
                                <td>{{ $role->id }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Name') }}</td>
                                <td>{{ $role->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Description') }}</td>
                                <td>{{ $role->description }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Default?') }}</td>
                                <td>{{ $role->default? "Default" : "Not default" }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Full access?') }}</td>
                                <td>{{ $role->active? "Yes, all control" : "No" }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Active?') }}</td>
                                <td>{{ $role->active? "Active" : "Inactive" }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Created at') }}</td>
                                <td>{{ $role->created_at }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Updated at') }}</td>
                                <td>{{ $role->updated_at }}</td>
                            </tr>
                        </table>

                        <a class='btn btn-secondary btn-sm' href={{ route('role.index') }}>Back to list</a>
                        <a class='btn btn-success btn-sm' href={{ route('role.edit', [$role->id]) }}>Edit</a>
                        <form action="{{ route('role.destroy', [$role->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                            @method('delete')
                            @csrf
                            <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection