routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/session/user', function () {
    return Auth::user();
})->name('session.user');

Route::get('/', 'WelcomeController@welcome')->name('welcome');
Route::get('/error', 'HomeController@error')->name('error');
Route::get('/forbidden', 'HomeController@forbidden')->name('forbidden');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/user/info', 'UserController@info')->name('info');
    Route::get('/user/balance', 'BalanceHistoryController@show')->name('balance');

    Route::group(['prefix' => 'admin'],function () {
        Route::resource('/role', 'RoleController')
            ->middleware('permission:admin role');

        Route::resource('/user', 'UserController')
            ->middleware('permission:admin user')
            ->except(['store', 'create']);
    });

    /*
     * Creator routes
     */
    Route::group(['prefix' => 'creator'], function () {
        Route::resource('/category', 'CategoryController')
            ->middleware('permission:creator category');

        Route::resource('/subcategory', 'SubcategoryController')
            ->middleware('permission:creator subcategory');

        Route::resource('/team', 'TeamController')
            ->middleware('permission:creator team');

        Route::resource('/event', 'EventController')
            ->middleware('permission:creator event')
            ->except(['create', 'store']);
    });

    /*
     * Company routes
     */
    Route::group(['prefix' => 'company'], function () {
        Route::get('/bets', 'BetController@index')
            ->middleware('permission:company all bets')
            ->name('company.bets');

        Route::get('/bets/open', 'BetController@companyOpenBets')
            ->middleware('permission:company open bets')
            ->name('company.open.bets');

        Route::get('/bets/closed', 'BetController@companyClosedBets')
            ->middleware('permission:company closed bets')
            ->name('company.closed.bets');

        Route::resource('/bonus', 'BonusController')
            ->middleware('permission:company bonus')
            ->only(['index', 'create', 'store']);

        Route::post('/bonus/activate/{bonus}', 'BonusController@activate')
            ->middleware('permission:company bonus activate')
            ->name('bonus.activate');

        Route::post('/bonus/deactivate}', 'BonusController@deactivate')
            ->middleware('permission:company bonus deactivate')
            ->name('bonus.deactivate');
    });

    /*
     *  Player routes
    */
    Route::group(['prefix' => 'player'], function () {
        Route::get('/events/available', 'EventController@showAvailableEvents')
            ->middleware('permission:player events and bets')
            ->name('player.available.events');

        Route::get('/bets/open', 'BetController@playerOpenBets')
            ->middleware('permission:player open bets')
            ->name('player.open.bets');

        Route::get('/bets/closed', 'BetController@playerClosedBets')
            ->middleware('permission:player closed bets')
            ->name('player.closed.bets');

        Route::get('/statistic', 'Statistic\PlayerController@index')
            ->middleware('permission:player statistic')
            ->name('player.statistic');
    });
});

app/Team.php
<?php

declare (strict_types=1);

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class Team
 *
 * @package App
 * @property-read Category $category
 * @property-read Subcategory $subcategory
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string $description
 * @property int $subcategory_id
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static Builder|Team whereCreatedAt($value)
 * @method static Builder|Team whereDescription($value)
 * @method static Builder|Team whereId($value)
 * @method static Builder|Team whereName($value)
 * @method static Builder|Team whereSubcategoryId($value)
 * @method static Builder|Team whereUpdatedAt($value)
 * @method static Builder|Team newModelQuery()
 * @method static Builder|Team newQuery()
 * @method static Builder|Team query()
 */
class Team extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'subcategory_id',
    ];

    /**
     * @return BelongsTo
     */
    public function subcategory(): BelongsTo
    {
        return $this->belongsTo(Subcategory::class);
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class, 'subcategory_id', 'id');
    }
}

app/Http/Controllers/TeamController.php
<?php

declare (strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\TeamStoreRequest;
use App\Http\Requests\TeamUpdateRequest;
use App\Repositories\CategoryRepository;
use App\Repositories\SubcategoryRepository;
use App\Repositories\TeamRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * Class TeamController
 * @package App\Http\Controllers
 */
class TeamController extends Controller
{
    /**
     * @var TeamRepository
     */
    private $teamRepository;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;
    /**
     * @var SubcategoryRepository
     */
    private $subcategoryRepository;

    public function __construct(TeamRepository $teamRepository, CategoryRepository $categoryRepository, SubcategoryRepository $subcategoryRepository)
    {
        $this->teamRepository = $teamRepository;
        $this->categoryRepository = $categoryRepository;
        $this->subcategoryRepository = $subcategoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     * @throws \Exception
     */
    public function index(): View
    {
        $teams = $this->teamRepository->with(['subcategory.category'])->paginate();

        return view('team.list', compact('teams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     * @throws \Exception
     */
    public function create(): View
    {
        $categories = $this->categoryRepository->all();
        $subcategories = $this->subcategoryRepository->all();

        return view('team.create', compact('categories', 'subcategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param TeamStoreRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(TeamStoreRequest $request): RedirectResponse
    {
        $this->teamRepository->create([
            'name' => $request->getName(),
            'description' => $request->getDescription(),
            'subcategory_id' => $request->getSubcategoryId(),
        ]);

        return redirect()
            ->route('team.index')
            ->with('status', 'Team created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $teamId
     * @return View
     * @throws \Exception
     */
    public function show(int $teamId): View
    {
        $team = $this->teamRepository->find($teamId);

        return view('team.view', compact('team'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $teamId
     * @return View
     * @throws \Exception
     */
    public function edit(int $teamId): View
    {
        $categories = $this->categoryRepository->all();
        $subcategories = $this->subcategoryRepository->all();
        $team = $this->teamRepository->find($teamId);

        return view('team.edit', compact('team', 'categories', 'subcategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param TeamUpdateRequest $request
     * @param int $teamId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(TeamUpdateRequest $request, int $teamId): RedirectResponse
    {
        $data = [
            'name' => $request->getName(),
            'description' => $request->getDescription(),
            'subcategory_id' => $request->getSubcategoryId(),
        ];

        $this->teamRepository->update($data, $teamId);

        return redirect()
            ->route('team.index')
            ->with('status', 'Team updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $teamId
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(int $teamId): RedirectResponse
    {
        $this->teamRepository->delete([$teamId]);

        return redirect()
            ->route('team.index')
            ->with('status', 'Team deleted successfully!');
    }
}

resources/views/team/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Team New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('team.store') }}" method="post">

                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description') }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="category_id">{{ __('Category') }}:</label>
                                <select name="category_id" id="category_id" class="form-control" onchange="createSubcategoriesOptions(this.value);">
                                    <option value="" selected disabled>Select category</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ (old('category_id') == $category->id)? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="alert-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="subcategory_id">{{ __('Subcategory') }}:</label>
                                <select name="subcategory_id" id="subcategory_id" class="form-control">
                                    <option disabled selected>Select subcategory</option>
                                </select>
                                @if($errors->has('subcategory_id'))
                                    <div class="alert-danger">{{ $errors->first('subcategory_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('team.index') }}>Back to list</a>
                            </div>

                        </form>
                        <script>
                            document.getElementById('category_id').addEventListener("load", createSubcategoriesOptions());
                            function createSubcategoriesOptions(id = null) {
                                if (id === null) {
                                    id = document.getElementById('category_id').value;
                                }
                                let subcategoriesArray =  JSON.parse('{!! $subcategories !!}');
                                document.getElementById('subcategory_id').innerHTML = '<option disabled selected>Select subcategory</option>';
                                subcategoriesArray.forEach(function(element) {
                                    if (element.category_id == id){
                                        let option = document.createElement("option");
                                        option.value = element.id;
                                        option.text = element.name;
                                        if (element.id == {!! old('subcategory_id', '""') !!}) {
                                            option.defaultSelected = true;
                                        }
                                        document.getElementById('subcategory_id').appendChild(option);
                                    }
                                });
                            }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/team/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Team New
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form action="{{ route('team.update', [$team->id]) }}" method="post">
                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name">{{ __('Name') }}:</label>
                                <input id="name" class="form-control" type="text" name="name"
                                       value="{{ old('name', $team->name) }}">
                                @if($errors->has('name'))
                                    <div class="alert-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="description">{{ __('Description') }}:</label>
                                <input id="description" class="form-control" type="text" name="description"
                                       value="{{ old('description', $team->description) }}">
                                @if($errors->has('description'))
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="category_id">{{ __('Category') }}:</label>
                                <select name="category_id" id="category_id" class="form-control" onchange="createSubcategoriesOptions(this.value);">
                                    <option value="" selected disabled>Select category</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ (old('category_id', $team->subcategory->category->id) == $category->id)? 'selected' : '' }}>
                                            {{ $category->name }}
                                        </option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="alert-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="subcategory_id">{{ __('Subcategory') }}:</label>
                                <select name="subcategory_id" id="subcategory_id" class="form-control">
                                    <option disabled selected>Select subcategory</option>
                                </select>
                                @if($errors->has('subcategory_id'))
                                    <div class="alert-danger">{{ $errors->first('subcategory_id') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input class="btn btn-success btn-sm" type="submit" value="{{ __('Save') }}">
                                <a class='btn btn-secondary btn-sm' href={{ route('team.index') }}>Back to list</a>
                            </div>

                        </form>
                        <script>
                            document.getElementById('category_id').addEventListener("load", createSubcategoriesOptions());
                            function createSubcategoriesOptions(id = null) {
                                if (id === null) {
                                    id = document.getElementById('category_id').value;
                                }
                                let subcategoriesArray =  JSON.parse('{!! $subcategories !!}');
                                document.getElementById('subcategory_id').innerHTML = '<option disabled selected>Select subcategory</option>';
                                subcategoriesArray.forEach(function(element) {
                                    if (element.category_id == id){
                                        let option = document.createElement("option");
                                        option.value = element.id;
                                        option.text = element.name;
                                        if (element.id == {!! old('subcategory_id', $team->subcategory_id) !!}) {
                                            option.defaultSelected = true;
                                        }
                                        document.getElementById('subcategory_id').appendChild(option);
                                    }
                                });
                            }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/team/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Teams List
                        <a class="btn btn-sm btn-primary" href="{{ route('team.create') }}">{{ __('New') }}</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Category</th>
                                <th>Subcategory</th>
                                <th>Actions</th>
                            </tr>
                            @foreach($teams as $team)
                                <tr>
                                    <td>{{ $team->id }}</td>
                                    <td>
                                        <a href="{{ route('team.show', [$team->id]) }}">
                                            {{ $team->name }}
                                        </a>
                                    </td>
                                    <td>{{ $team->description }}</td>
                                    <td>{{ $team->subcategory->category->name }}</td>
                                    <td>{{ $team->subcategory->name }}</td>
                                    <td>
                                        <a class='btn btn-sm btn-info' href="{{ route('team.show', [$team->id]) }}">{{ __('View') }}</a>
                                        <a class='btn btn-sm btn-success' href="{{ route('team.edit', [$team->id]) }}">{{ __('Edit') }}</a>
                                        <form action="{{ route('team.destroy', [$team->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                                            @method('delete')
                                            @csrf
                                            <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        {{ $teams->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/team/view.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        Team View: {{ $team->Name }}
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table">
                            <tr>
                                <td>{{ __('ID') }}</td>
                                <td>{{ $team->id }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Name') }}</td>
                                <td>{{ $team->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Description') }}</td>
                                <td>{{ $team->description }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Category') }}</td>
                                <td>{{ $team->subcategory->category->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Subcategory') }}</td>
                                <td>{{ $team->subcategory->name }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Created at') }}</td>
                                <td>{{ $team->created_at }}</td>
                            </tr>
                            <tr>
                                <td>{{ __('Updated at') }}</td>
                                <td>{{ $team->updated_at }}</td>
                            </tr>
                        </table>

                        <a class='btn btn-secondary btn-sm' href={{ route('team.index') }}>Back to list</a>
                        <a class='btn btn-success btn-sm' href={{ route('team.edit', [$team->id]) }}>Edit</a>
                        <form action="{{ route('team.destroy', [$team->id]) }}" method="post" class="d-inline-block" onsubmit="return confirm('Do you really want to delete?');">
                            @method('delete')
                            @csrf
                            <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection